language: android
jdk: oraclejdk8
# Use the Travis Container-Based Infrastructure
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_EMULATOR_SDK_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_EMULATOR_SDK_LEVEL
    # For Google APIs
    - addon-google_apis-google-$ANDROID_EMULATOR_SDK_LEVEL
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_SDK_LEVEL

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_SDK_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-window &
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh
  - adb devices
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean check connectedCheck -PdisablePreDex --stacktrace