language: android
sudo: false
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

env:
  global:
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=24.0.3
  matrix:
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
  - emulator -avd test -no-window &
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh
  - adb devices
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck