language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tool
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME

script:
  - ./gradlew clean jacocoDebugTestReport