language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20
    - BUILD_TOOLS_VERSION=26.0.0
    - EMULATOR_SDK_LEVEL=25
    - TAG=google_apis
    - TARGET_SDK_LEVEL=26

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-EMULATOR_SDK_LEVEL
    - android-TARGET_SDK_LEVEL
    - sys-img-$ABI-addon-google_apis-google-$EMULATOR_SDK_LEVEL
    - sys-img-$ABI-addon-google_apis-google-$TARGET_SDK_LEVEL
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_SDK_LEVEL --abi $ABI --tag $TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait 60 ./gradlew clean connectedAndroidTest -PdisablePreDex --stacktrace