language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
#    - ANDROID_MIN_API_LEVEL=16
#    - ANDROID_MAX_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.0
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
  matrix:
    - API=android-16 ABI=armeabi-v7a
    - API=android-26 ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-16
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

before_script:
  - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $API --abi $ABI
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait 60 ./gradlew clean connectedAndroidTest -PdisablePreDex --stacktrace