language: android
jdk: oraclejdk8
sudo: required
dist: trusty

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - $HOME/.gradle/caches/3.5
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

env:
  matrix:
    - EMULATOR_SDK_LEVEL=16 ABI=armeabi-v7a
    - EMULATOR_SDK_LEVEL=24 ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=20
    - BUILD_TOOLS_VERSION=26.0.0
    - TARGET_SDK_LEVEL=26

android:
  components:
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$EMULATOR_SDK_LEVEL
    - android-$TARGET_SDK_LEVEL
    - sys-img-$ABI-android-$EMULATOR_SDK_LEVEL
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

before_script:
  - echo no | android create avd --force --name test --target android-$EMULATOR_SDK_LEVEL --abi $ABI
  - emulator -avd test -no-audio -no-window &
  - ./gradlew check --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - travis_wait 60 ./gradlew connectedAndroidTest --stacktrace

after_success:
  - ./gradlew jacocoDebugReport
  - pip install --user codecov
  - codecov