language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=26
    - EMULATOR_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=26.0.0
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script: travis_wait 60 ./gradlew clean connectedAndroidTest -PdisablePreDex --stacktrace