language: android
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - sys-img-arm64-v8a-google_apis-25

env:
  matrix:
    - $TARGET=android-25 ABI=google_apis/arm64-v8a
#    - API=android-17 ABI=armeabi-v7a
#    - API=android-18 ABI=armeabi-v7a
#    - API=android-19 ABI=armeabi-v7a
#    - API=android-20 ABI=armeabi-v7a
#    - API=android-21 ABI=armeabi-v7a
#    - API=android-22 ABI=armeabi-v7a
#    - API=android-24 ABI=armeabi-v7a
#    - API=android-25 ABI=armeabi-v7a
#    - API=android-26 ABI=armeabi-v7a

before_script:
  - echo no | android create avd --force -name test -target $TARGET --abi $ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean assembleDebug assembleDebugAndroidTest
  - travis_wait 60 ./gradlew connectedDebugAndroidTest --stacktrace
  - ./gradlew jacocoDebugReport

after_success:
  - bash <(curl -s https://codecov.io/bash)