language: android
jdk: oraclejdk8

sudo: required

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-24
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-24

env:
  matrix:
    - $TARGET=android-24 ABI=armeabi-v7a

before_script:
  - echo $JAVA_OPTS
  - export JAVA_OPTS=-Xmx2048m
  - android list targets
  - echo no | android create avd --force -n test -t $TARGET --abi $ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean assembleDebug assembleDebugAndroidTest
  - travis_wait 60 ./gradlew connectedDebugAndroidTest --stacktrace
  - ./gradlew jacocoDebugReport

after_success:
  - bash <(curl -s https://codecov.io/bash)