language: android
jdk: oraclejdk8
sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  matrix:
    - EMULATOR_SDK_LEVEL=16 ABI=armeabi-v7a
    - EMULATOR_SDK_LEVEL=25 ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=20
    - BUILD_TOOLS_VERSION=26.0.0
    - TAG=google_apis
    - TARGET_SDK_LEVEL=26

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - platform-tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$EMULATOR_SDK_LEVEL
    - android-$TARGET_SDK_LEVEL
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

before_script:
  - android-update-sdk --components=sys-img-$ABI-google_apis-$EMULATOR_SDK_LEVEL --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $EMULATOR_SDK_LEVEL --abi $ABI
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait 60 ./gradlew clean jacocoDebugTestReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)